<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="timetables" nsURI="timetables" nsPrefix="timetables">
  <eClassifiers xsi:type="ecore:EClass" name="Timetables">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timetables" upperBound="-1"
        eType="#//Timetable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" upperBound="-1"
        eType="#//Subject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classrooms" upperBound="-1"
        eType="#//Classroom" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classroom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timetable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="degree" eType="#//Degree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
        eType="#//Slot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="#//Day"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//Subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Day">
    <eLiterals name="MONDAY"/>
    <eLiterals name="TUESDAY" value="1"/>
    <eLiterals name="WEDNESDAY" value="2"/>
    <eLiterals name="THURSDAY" value="3"/>
    <eLiterals name="FRIDAY" value="4"/>
    <eLiterals name="SATURDAY" value="5"/>
    <eLiterals name="SUNDAY" value="6"/>
  </eClassifiers>
</ecore:EPackage>
